appenders:
    stdout:
        kind: console
        encoder:
            pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
        filters:
            - kind: threshold
              level: info
    file:
      kind: file
      path: log/spmm_log.log
      append: true
    rolling_file:
        kind: rolling_file
        path: log/spmm_rolling.log
        append: true
        encoder:
          pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
        policy:
          kind: compound
          trigger:
            kind: size
            limit: 10Mb
          roller:
            kind: fixed_window
            pattern: log/spmm_rolling.{}.log
            count: 5
            base: 1
        filters:
            - kind: threshold
              level: info
root:
    level: trace
    appenders:
        - rolling_file
        - stdout