appenders:
    stdout:
        kind: console
    file:
      kind: file
      path: log/spmm_log_debug.log
      append: false
    rolling_file:
        kind: rolling_file
        path: log/spmm_rolling_debug.log
        append: true
        policy:
          kind: compound
          trigger:
            kind: size
            limit: 10Mb
          roller:
            kind: fixed_window
            pattern: log/spmm_rolling_debug.{}.log
            count: 5
            base: 1

root:
    level: debug
    appenders:
        - rolling_file
        - stdout
        - file