appenders:
    stdout:
        kind: console
        encoder:
            pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"

    file:
      kind: file
      path: log/spmm_log.log
      append: false
    rolling_file:
        kind: rolling_file
        path: log/spmm_rolling.log
        append: true
        encoder:
          pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
        policy:
          kind: compound
          trigger:
            kind: size
            limit: 10Mb
          roller:
            kind: fixed_window
            pattern: log/spmm_rolling.{}.log
            count: 5
            base: 1

root:
    level: info
    appenders:
        - rolling_file
        - stdout
        - file
loggers:
  spmm_pim::sim:
    level: info
  # spmm_pim::sim::partial_sum_collector:
  #   level: debug
  # spmm_pim::sim::partial_sum_sender:
  #   level: debug
  # spmm_pim::sim::partial_sum_signal_collector:
  #   level: debug
  # spmm_pim::sim::merger_task_dispather:
  #   level: debug
  # spmm_pim::sim::full_result_merger_worker:
  #   level: debug
  # spmm_pim::sim::task_sender::histo:
  #   level: debug
  # spmm_pim::sim::merger_task_sender::timeerror:
  #   level: debug