[[all]]
file = "test.mtx"
c = 64
origin_nnz = 9
new_nnz = 6
new_element = 384
need_speed_up = 42.666668

[[all]]
file = "test.mtx"
c = 128
origin_nnz = 9
new_nnz = 6
new_element = 768
need_speed_up = 85.333336

[[all]]
file = "test.mtx"
c = 256
origin_nnz = 9
new_nnz = 6
new_element = 1536
need_speed_up = 170.66667

[[all]]
file = "test.mtx"
c = 512
origin_nnz = 9
new_nnz = 6
new_element = 3072
need_speed_up = 341.33334

[[all]]
file = "test.mtx"
c = 1024
origin_nnz = 9
new_nnz = 6
new_element = 6144
need_speed_up = 682.6667

[[all]]
file = "test.mtx"
c = 2048
origin_nnz = 9
new_nnz = 6
new_element = 12288
need_speed_up = 1365.3334
