[mem_settings]
row_size = 512
banks = 8
chips = 8
channels = 2
row_mapping = "Chunk"
bank_merger_size = 16
chip_merger_size = 8
channel_merger_size = 8
dimm_merger_size = 8
simd_width = 8
parallel_count=8
reorder_count=8