mtx_files = [
    "mtx/1c.mtx",
    "mtx/GD98_a.mtx",
    "mtx/Tina_AskCal_perm.mtx",
    "mtx/arrowc.mtx",
    "mtx/bcspwr03.mtx",
    "mtx/bfwa62.mtx",
    "mtx/cs.mtx",
    "mtx/fullcrud2.mtx",
    "mtx/lp_e226.mtx",
    "mtx/mangle4.mtx",
    "mtx/s32.mtx",
    "mtx/3by0.mtx",
    "mtx/GD99_cc.mtx",
    "mtx/Trec4.mtx",
    "mtx/ash219.mtx",
    "mtx/bcspwr04.mtx",
    "mtx/big           csa.mtx",
    "mtx/fullcsa.mtx",
    "mtx/lp_e226_transposed.mtx",
    "mtx/one.mtx",
    "mtx/two.mtx",
    "mtx/Erdos971.mtx",
    "mtx/Groebner_id2003_aug.mtx",
    "mtx/a0.mtx",
    "mtx/b1_ss.mtx",
    "mtx/bcspwr05.mtx",
    "mtx/c.mtx",
    "mtx/ctina.mtx",
    "mtx/fullcza.mtx",
    "mtx/lp_share1b.mtx",
    "mtx/onec.mtx",
    "mtx/w156.mtx",
    "mtx/Franz6_id1959_aug.mtx",
    "mtx/LFAT5.mtx",
    "mtx/a04.mtx",
    "mtx/bad_dimensions.mtx",
    "mtx/bcspwr06.mtx",
    "mtx/c2.mtx",
    "mtx/cza.mtx",
    "mtx/fullrsa.mtx",
    "mtx/lpi_galenet.mtx",
    "mtx/plskz362.mtx",
    "mtx/west0067.mtx",
    "mtx/G51.mtx",
    "mtx/NotreDame_www.mtx",
    "mtx/a1.mtx",
    "mtx/bad_header.mtx",
    "mtx/bcspwr07.mtx",
    "mtx/c32.mtx",
    "mtx/dwt_992.mtx",
    "mtx/fullrza.mtx",
    "mtx/lpi_itest6.mtx",
    "mtx/pts5ldd03.mtx",
    "mtx/young1c.mtx",
    "mtx/GD01_b.mtx",
    "mtx/Pd.mtx",
    "mtx/a2.mtx",
    "mtx/bad_matrix_type.mtx",
    "mtx/bcspwr08.mtx",
    "mtx/can___24.mtx",
    "mtx/fullcha.mtx",
    "mtx/impcol_a.mtx",
    "mtx/mangle1.mtx",
    "mtx/pwr01b.mtx",
    "mtx/GD06_theory.mtx",
    "mtx/Ragusa16.mtx",
    "mtx/a4.mtx",
    "mtx/bcspwr01.mtx",
    "mtx/bcspwr09.mtx",
    "mtx/cha.mtx",
    "mtx/fullcrud.mtx",
    "mtx/jagmesh7.mtx",
    "mtx/mangle2.mtx",
    "mtx/r2.mtx",
    "mtx/GD97_b.mtx",
    "mtx/Tina_AskCal.mtx",
    "mtx/arrow.mtx",
    "mtx/bcspwr02.mtx",
    "mtx/bcspwr10.mtx",
    "mtx/cover.mtx",
    "mtx/fullcrud1.mtx",
    "mtx/lfat5b.mtx",
    "mtx/mangle3.mtx",
    "mtx/rza.mtx",
]

result_file = "all_size.json"
